### ISSUE TITLE
P4 Testing

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/Intro-Object-Oriented-Programming-Playground#14]
![image](https://cloud.githubusercontent.com/assets/3460171/15950144/121f7ff0-2e61-11e6-8f8d-641a2bd36279.png)

We should add  bear.sleep()
at the end of the test code in order to have the last line of the comparison test display "Pooh hibernates for 4 months"

**Comment by dionlarson** [comment]
Read spec again -- made a bit more clear in fe9e8e3
