### ISSUE TITLE
P6 Testing Class/instance name

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/Intro-Object-Oriented-Programming-Playground#23]
![image](https://cloud.githubusercontent.com/assets/3460171/15950775/c79c1bd6-2e66-11e6-8f99-06581495fe4a.png)
In the testing in the end, I think that the variable name should not be the kind of animal but the name of the animal, after all this is an instance of that animal: This specific animal is Tigger, it is only of type tiger, so the variable name should be Tigger. I would make this change so that the students are taught more proper variable naming, and so that it is clear that we can make more variables of type tiger but which have different names.

**Comment by cliffweitzman** [comment]
Also, we should add a "Pooh hibernates for 4 months" after "YUM!!! Pooh wants more fish" in he commented out code because our animals automatically go to sleep after they eat.
![image](https://cloud.githubusercontent.com/assets/3460171/15950851/84bda22a-2e67-11e6-98d7-f01c2288e790.png)

**Comment by dionlarson** [comment]
See spec in P4 for better clarification -- also fixing test code to catch this misunderstanding earlier
