### ISSUE TITLE
Next / Prev

### ISSUE THREAD

**Issue by esscbee** [MakeSchool-Tutorials/Intro-Object-Oriented-Programming-Playground#3]
Should the bottom of the pages have a "Previous" link?

**Comment by dionlarson** [comment]
I am still undecided on how to link pages. Will probably create table of contents and follow conventions in the Swift-Language playgrounds (link to all three at bottom of each page).

**Comment by dionlarson** [comment]
Fixed in c7da86b. Went with next/prev on bottom only but no table contents.
