### ISSUE TITLE
Overall Experience of solving problems and seeing the answers

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Intro-Object-Oriented-Programming-Playground#31]
While the content in the playgrounds is neat, it seems to get in the way of seeing the answers and working with the code. I love the idea of interactive coding documents, the experience I'm getting is not living up to the potential.

I feel it we need to make sure that students understand that they need to open console below. We need to make sure students will open the console and look for the output there. 

It might be better to have students create a new playground for each example, and move the tutorial lesson text out of playgrounds. This would prevent confusion that might come from having to copy and paste  elements from previous lessons into a new lesson to continue. This would also avoid problems where students might try to place code in areas where it isn't allowed. 

The suggestion above might be too much work at this point, an alternative might be to move the challenges each to their own page with only code and comments. 

Might be good to add a short description of the error and warning icons in the left column. 

Red Stop Sign - This is an error. You must fit this before continuing. Click it to read the error message provided by the compiler. 

Red Stop Sign with white dot - This is an error. You must fix this before continuing. Luckily the compiler has a suggested solution. Click it to see the solution. You can double click the solution popup to apply. 

Yellow Triangle - This is warning. The compiler is telling that it sees something questionable or it has a suggestion. Click this to read the suggestion.

**Comment by dionlarson** [comment]
They will have a crash guide to playgrounds in their online interface. Including how to get it working if it is failing in harder to understand ways.
