### ISSUE TITLE
P7 Final Problem a bit confusing 

### ISSUE THREAD

**Issue by danstepanov** [MakeSchool-Tutorials/Intro-Object-Oriented-Programming-Playground#37]
See the below image. I believe the prompt 

```
Great! Now, we're ready to create a Zookeeper class that contains a name instance variable and 
an initializer method that sets name using an argument. A zookeeper needs to feed many animals 
each day, so let's add a feedAnimals method, which should take two arguments: animals – an array 
of Animals, and food – a string. This method should first print "<name> is feeding <food> to 
<animals.count> animals", then iterate over the array of animals and call each animal's eat method, 
passing the value of food as the argument.

Finally, call this feedAnimals method, using an array containing an instance of each animal, and 
your own favorite food.
```

can confuse the student a bit. See my code within the same image below. I try to only use things I pick up within the tutorials to solve these problems and based on that, I feel I'm ill equipped without a bit more of a hint as to the solution. Dion, perhaps you could provide a loosely structured for loop? 

<img width="1392" alt="screen shot 2016-06-13 at 6 23 38 pm" src="https://cloud.githubusercontent.com/assets/5482800/16028442/2798f7e0-3194-11e6-8ba2-f178a61aead5.png">

**Comment by dionlarson** [comment]
Arrays & loops is before this in the curriculum so I believe it is fine.
